/**
 * ═══════════════════════════════════════════════════════════════════════════
 * WS Protocol — Reliable Messaging Layer
 *
 * Defines the canonical message envelope, all event identifiers, and shared
 * configuration constants used by both the server (ws-server.ts) and every
 * client instance (ws-client.ts / useWsMessaging.ts).
 *
 * Design axioms:
 *   • Every frame that crosses the wire uses MessageEnvelope — no naked JSON.
 *   • Event names are string-union–typed so the compiler catches typos.
 *   • Retry / heartbeat constants live here; changing them in one place
 *     propagates everywhere.
 * ═══════════════════════════════════════════════════════════════════════════
 */

// ── Envelope ──────────────────────────────────────────────────────────────────

/**
 * The canonical wire frame for every user-level message.
 *
 * @property id        - UUID v4, generated by the sender. Primary idempotency key.
 * @property clientId  - Stable device identifier (persisted in localStorage).
 * @property convoId   - Target conversation UUID.
 * @property senderId  - Auth user UUID of the originator.
 * @property tsClient  - Unix-ms timestamp when the client created the frame.
 * @property tsServer  - Unix-ms timestamp stamped by the server on receipt (0 on client).
 * @property seq       - Monotonically-increasing per-conversation sequence number.
 *                       Assigned by the server; the client sends 0 as a placeholder.
 * @property payload   - Opaque application data (message body, reaction, etc.).
 */
export interface MessageEnvelope {
  id: string;
  clientId: string;
  convoId: string;
  senderId: string;
  tsClient: number;
  tsServer: number;
  seq: number;
  payload: unknown;
}

// ── Control frames ────────────────────────────────────────────────────────────

/** Sent by the server → client to acknowledge a stored message. */
export interface DeliveredFrame {
  type: 'delivered';
  id: string;       // original MessageEnvelope.id
  seq: number;      // authoritative sequence number assigned by the server
  tsServer: number;
}

/** Sent by the server → sender once the recipient has ACK'd the message. */
export interface SeenFrame {
  type: 'seen';
  id: string;
  convoId: string;
  seenBy: string;   // recipientId
  tsServer: number;
}

/** Sent by a connected client to acknowledge receipt of a server-push message. */
export interface RecipientAckFrame {
  type: 'ack';
  id: string;       // MessageEnvelope.id being acknowledged
  convoId: string;
}

/** Sent by the server to replay missing messages after reconnection. */
export interface ReplayFrame {
  type: 'replay';
  convoId: string;
  messages: MessageEnvelope[];
}

/** Sync frame: server tells a reconnecting client its authoritative last seq. */
export interface SyncFrame {
  type: 'sync';
  convoId: string;
  lastSeq: number;
}

/** Typing indicator broadcast. */
export interface TypingFrame {
  type: 'typing';
  convoId: string;
  senderId: string;
  isTyping: boolean;
}

/** Heartbeat ping from client → server. */
export interface PingFrame {
  type: 'ping';
  ts: number;
}

/** Heartbeat pong from server → client. */
export interface PongFrame {
  type: 'pong';
  ts: number;      // echo of the ping.ts so client can measure RTT
  serverTs: number;
}

/** Union of every frame type that can cross the wire. */
export type WireFrame =
  | ({ type: 'message' } & MessageEnvelope)
  | DeliveredFrame
  | SeenFrame
  | RecipientAckFrame
  | ReplayFrame
  | SyncFrame
  | TypingFrame
  | PingFrame
  | PongFrame;

// ── Event Names ───────────────────────────────────────────────────────────────

/**
 * Canonical event names — the single source of truth for every event string
 * used anywhere in the stack.  Import WsEvent and use WsEvent.Send etc. to
 * prevent magic-string drift between client and server.
 */
export const WsEvent = {
  /** Client sends a new message to the server. */
  Send: 'message',

  /** Server → client: message persisted, ACK with server-assigned seq. */
  Delivered: 'delivered',

  /** Server → sender: recipient acknowledged the message. */
  Seen: 'seen',

  /** Recipient → server: raw ACK for a push-delivered message. */
  Ack: 'ack',

  /** Client → server on reconnect: "give me everything after seq N". */
  Sync: 'sync',

  /** Server → client: replay of missed messages. */
  Replay: 'replay',

  /** Bidirectional typing indicator. */
  Typing: 'typing',

  /** Client → server heartbeat. */
  Ping: 'ping',

  /** Server → client heartbeat reply. */
  Pong: 'pong',
} as const;

export type WsEventName = typeof WsEvent[keyof typeof WsEvent];

// ── Configuration ─────────────────────────────────────────────────────────────

export const WsConfig = {
  /** Milliseconds before an unACK'd message is retried. */
  ACK_TIMEOUT_MS: 2_000,

  /** Maximum number of delivery attempts per message. */
  MAX_RETRIES: 3,

  /**
   * Exponential-backoff multiplier.
   * Attempt 0 → ACK_TIMEOUT_MS × 1 = 2 s
   * Attempt 1 → ACK_TIMEOUT_MS × 2 = 4 s
   * Attempt 2 → ACK_TIMEOUT_MS × 4 = 8 s
   */
  BACKOFF_FACTOR: 2,

  /** Milliseconds between client-initiated heartbeat pings. */
  PING_INTERVAL_MS: 15_000,

  /**
   * Milliseconds after the last pong before the client declares the
   * connection dead and initiates a reconnect.
   */
  PONG_TIMEOUT_MS: 30_000,

  /** Base delay for WS reconnect attempts (doubles each attempt, max 30 s). */
  RECONNECT_BASE_MS: 1_000,

  /** Hard cap on reconnect backoff delay. */
  RECONNECT_MAX_MS: 30_000,
} as const;

// ── Helpers ───────────────────────────────────────────────────────────────────

/** Returns true if a WireFrame is a user-level MessageEnvelope. */
export function isMessageFrame(f: WireFrame): f is { type: 'message' } & MessageEnvelope {
  return f.type === WsEvent.Send;
}

/** Serialise a WireFrame for transmission. */
export function encodeFrame(frame: WireFrame): string {
  return JSON.stringify(frame);
}

/** Deserialise raw WebSocket data to a typed WireFrame, or null on error. */
export function decodeFrame(raw: unknown): WireFrame | null {
  try {
    const str = typeof raw === 'string' ? raw : String(raw);
    const obj = JSON.parse(str);
    if (typeof obj?.type !== 'string') return null;
    return obj as WireFrame;
  } catch {
    return null;
  }
}
