'use client';

import { useState, useTransition, useEffect } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { ShieldCheck, Loader2, ArrowRight, ArrowLeft, KeyRound, AlertCircle } from 'lucide-react';
import { motion } from 'framer-motion';
import { verifyLoginMFAAction, verifyLoginRecoveryCodeAction } from '../actions';

export default function LoginMFAContent() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const factorId = searchParams.get('factorId') || '';
  const email = searchParams.get('email') || '';

  const [otpCode, setOtpCode] = useState('');
  const [error, setError] = useState<string | null>(null);
  const [isRecoveryMode, setIsRecoveryMode] = useState(false);
  const [recoveryCode, setRecoveryCode] = useState('');

  const [isPending, startTransition] = useTransition();

  useEffect(() => {
    if (!factorId) {
      router.push('/login');
    }
  }, [factorId, router]);

  const handleVerify = () => {
    if (!otpCode || otpCode.length !== 6 || isNaN(Number(otpCode))) {
      setError('Please enter a valid 6-digit authentication code.');
      return;
    }

    setError(null);
    startTransition(async () => {
      const res = await verifyLoginMFAAction(factorId, otpCode);
      if (res.success) {
        router.push('/feed');
      } else {
        setError(res.error || 'Verification failed. Please check the code and try again.');
      }
    });
  };

  const handleVerifyRecovery = () => {
    if (!recoveryCode.trim()) {
      setError('Please enter your recovery code.');
      return;
    }

    setError(null);
    startTransition(async () => {
      const res = await verifyLoginRecoveryCodeAction(recoveryCode.trim(), factorId);
      if (res.success) {
        // Recovery unenrolls MFA, logging user in at AAL1 level
        router.push('/feed');
      } else {
        setError(res.error || 'Invalid recovery code. Please try again.');
      }
    });
  };

  return (
    <motion.div 
      initial={{ opacity: 0, y: 30 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.8, ease: [0.16, 1, 0.3, 1] }}
      className="w-full max-w-md bg-zinc-900/40 p-8 rounded-3xl border border-white/5 backdrop-blur-xl relative z-10 flex flex-col shadow-2xl"
    >
      <div className="flex flex-col items-center text-center">
        <div className="w-16 h-16 rounded-2xl bg-purple-500/10 flex items-center justify-center mb-6 border border-purple-500/20 text-purple-400">
          <ShieldCheck className="w-8 h-8" />
        </div>
        
        <h1 className="text-2xl font-bold text-white mb-2 tracking-tight">Two-Factor Authentication</h1>
        <p className="text-zinc-500 text-xs mb-8 max-w-[320px] leading-relaxed">
          {isRecoveryMode 
            ? 'Enter one of your 10 backup recovery codes (VR-XXXX-XXXX) to bypass authenticator verification.' 
            : `Enter the 6-digit code generated by your Authenticator app for ${email}.`}
        </p>
      </div>

      <div className="space-y-5">
        {!isRecoveryMode ? (
          <div className="space-y-2">
            <label className="text-[10px] font-bold uppercase tracking-[0.2em] text-neutral-500 ml-1">Authentication Code</label>
            <input
              type="text"
              maxLength={6}
              placeholder="000000"
              value={otpCode}
              onChange={e => setOtpCode(e.target.value.replace(/[^0-9]/g, ''))}
              onKeyDown={e => e.key === 'Enter' && handleVerify()}
              disabled={isPending}
              className="w-full text-center tracking-[12px] bg-white/[0.03] border border-white/5 focus:border-purple-500/30 focus:bg-white/[0.05] rounded-xl py-3.5 text-xl font-bold font-mono text-white focus:outline-none placeholder-neutral-700 transition-all"
            />
          </div>
        ) : (
          <div className="space-y-2">
            <label className="text-[10px] font-bold uppercase tracking-[0.2em] text-neutral-500 ml-1">Backup Recovery Code</label>
            <input
              type="text"
              placeholder="VR-0000-0000"
              value={recoveryCode}
              onChange={e => setRecoveryCode(e.target.value)}
              onKeyDown={e => e.key === 'Enter' && handleVerifyRecovery()}
              disabled={isPending}
              className="w-full text-center bg-white/[0.03] border border-white/5 focus:border-purple-500/30 focus:bg-white/[0.05] rounded-xl py-3.5 text-sm font-bold font-mono text-white focus:outline-none placeholder-neutral-700 transition-all"
            />
          </div>
        )}

        {error && (
          <div className="p-4 rounded-xl flex items-start gap-3 bg-rose-500/10 border border-rose-500/20 text-rose-500">
            <AlertCircle size={16} className="shrink-0 mt-0.5" />
            <span className="text-[11px] font-bold uppercase tracking-widest leading-relaxed">{error}</span>
          </div>
        )}

        <button 
          type="button" 
          onClick={isRecoveryMode ? handleVerifyRecovery : handleVerify}
          disabled={isPending}
          className="w-full flex items-center justify-center gap-2 bg-white text-black font-extrabold text-[13px] py-4 px-4 rounded-xl hover:bg-zinc-200 transition-colors disabled:opacity-50"
        >
          {isPending ? (
            <Loader2 className="w-5 h-5 animate-spin" />
          ) : (
            <>
              <span>Verify Identity</span>
              <ArrowRight size={14} />
            </>
          )}
        </button>
      </div>

      <div className="mt-8 pt-6 border-t border-white/5 w-full flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <button 
          type="button" 
          onClick={() => {
            setIsRecoveryMode(!isRecoveryMode);
            setError(null);
          }}
          disabled={isPending}
          className="flex items-center justify-center gap-1.5 text-xs text-purple-400 hover:text-purple-300 font-bold transition-colors"
        >
          <KeyRound className="w-4 h-4" />
          {isRecoveryMode ? 'Use Authenticator Code' : 'Use Backup Recovery Code'}
        </button>

        <button 
          type="button" 
          onClick={() => router.push('/login')}
          disabled={isPending}
          className="flex items-center justify-center gap-1.5 text-xs text-zinc-500 hover:text-white font-bold transition-colors"
        >
          <ArrowLeft className="w-4 h-4" />
          Cancel and Return
        </button>
      </div>
    </motion.div>
  );
}
